
var myName = "Andi";
console.log(myName);
myName = 9;
console.log(myName);


if(4 + 4 === 3) {
  console.log ('This Was True')
} else {
  console.log ('This Was False')
}

if(4 + 4 === 10) {
  console.log ('This Was True')
} else if (2 +2 === 4){
  console.log ('This is Also True')
} else {
  console.log ('This is False');
}

var numberOne = 8;
var numberTwo = 10;

console.log(numberOne, " This is numberOne");
console.log(numberTwo, " This is numberTwo");

if (numberOne + numberTwo ==== 18) {
  console.log ('True');
} else {
  console.log ('False');
}
